name: stream_feed
description: Stream Feed official Dart SDK. Build your own feed experience using
  Dart and Flutter.
version: 0.6.0+2
repository: https://github.com/GetStream/stream-feed-flutter
issue_tracker: https://github.com/GetStream/stream-feed-flutter/issues
homepage: https://getstream.io/
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dio: ^5.6.0
  equatable: ^2.0.5
 
  http_parser: ^4.0.2
  intl: ^0.19.0
  jose: ^0.3.2  # Reverted to valid version
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.11.0
  mime: ^2.0.0  # Key fix for original conflict

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  test: ^1.24.6
